# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 5 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - chrome-min-version: 49
         - chrome-min-version: 999
    env:
      CHROME_MIN_VERSION: ${{ matrix.chrome-min-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Show history
      run: git log --oneline -n 5
    - name: Install deps
      run: |
        google-chrome --version
        sudo -E ./install-build-deps.sh
    - name: Check environment
      run: |
        which java
        java -Xmx32m -version
        javac -J-Xmx32m -version
        google-chrome --version
    - name: Run pre-commit tests
      run: hooks/pre-commit
    - name: Run tests
      run: ant test -Dtest.shuffle=1 -Dtest.repeat=10
    - name: Package
      run: ant package
    - name: Create standalone JavaScript
      run: ant extractjs
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: domdistiller.js
        path: out/domdistiller.js
